/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'variantId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const CustomerInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
});
export const Order = IDL.Record({
  'customerInfo' : CustomerInfo,
  'orderId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([CartItem], [], []),
  'clearCart' : IDL.Func([], [], []),
  'fetchAliExpressProduct' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'placeOrder' : IDL.Func([CustomerInfo, IDL.Nat], [IDL.Text], []),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({
    'productId' : IDL.Text,
    'variantId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const CustomerInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
  });
  const Order = IDL.Record({
    'customerInfo' : CustomerInfo,
    'orderId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([CartItem], [], []),
    'clearCart' : IDL.Func([], [], []),
    'fetchAliExpressProduct' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'placeOrder' : IDL.Func([CustomerInfo, IDL.Nat], [IDL.Text], []),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };